// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import sink "github.com/rafalmnich/exporter/sink"

// Importer is an autogenerated mock type for the Importer type
type Importer struct {
	mock.Mock
}

// Import provides a mock function with given fields: ctx
func (_m *Importer) Import(ctx context.Context) ([]*sink.Reading, error) {
	ret := _m.Called(ctx)

	var r0 []*sink.Reading
	if rf, ok := ret.Get(0).(func(context.Context) []*sink.Reading); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sink.Reading)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
